import pathlib

p = pathlib.Path(r'd:\MyCode\YuTong-Java-Vue\YuTong-Java-Docs\23-设计到落地追踪记录\23-设计到落地追踪记录.md')
rows = """| 2026-07-23 | v1.0 GA2 前端 Web 端口迁移冒烟测试 | web-admin Vite dev server 端口由 5173 迁移至 5183，host 显式 0.0.0.0，API proxy target 对齐 Docker 后端 8082；8/8 PASS | （1）修改 `web-admin/vite.config.ts`：port 5173→5183、host true→'0.0.0.0'、proxy target `http://localhost:8080`→`http://localhost:8082`；同步修改 `web-admin/vite.config.js`；（2）修改 `tools/p2/failure-handling.yaml` 端口占用清单 5173/5174→5183/5184；（3）修复 23 号文档 line 203 Demo 数据状态与 line 179 GA2-L178 Done 矛盾，统一为 Done；（4）冒烟 8/8 PASS：T1 Vite 5183 启动、T2 localhost 访问 200、T3 外部 IP 192.168.31.74 访问 200、T4 admin_demo 前端代理登录 200、T5 viewer_demo 外部 IP 登录 200、T6 5173 无占用/5183 被 node.exe 占用、T7 backend 8082 health UP、T8 文档一致性修复。已知偏差：DEV-L179-001 深度验收记录章节未同步 GA2-L165~L178（后续批次补齐）；DEV-L179-002 docs-site 端口 5180 未纳入本次迁移（无冲突报告）。验收结论：**PASS**。 | `10-项目总体计划`、`20-DevOps与部署设计`、`82-环境变量与密钥管理规范详设`、`86-P2命令模板与执行记录详设`、`23` |
| 2026-07-23 | v1.0 GA2 CT-createCustomer 契约测试套件落地验收 | 新建 CT 基础设施与 createCustomer 契约测试，11/11 PASS（10 执行 + 1 Skipped） | （1）新建 5 个文件：`backend/yutong-boot/src/test/java/com/yutong/boot/contract/AbstractContractTest.java`（CT 基类）、`CTCreateCustomerTest.java`（10 个用例）、`application-test.yml`（复用 Docker 容器）、`RealtimePropertiesConfiguration.java`（独立注册 RealtimeProperties）、`evidence/GA2-L180/smoke-test-result.md`；（2）修改 6 个文件：`backend/pom.xml` + `yutong-boot/pom.xml` 追加 testcontainers/webmvc-test 依赖；`WebSocketConfig.java` 移除 @EnableConfigurationProperties；`CustomerService.java` 错误码 SYS_BUSINESS_CONFLICT→BIZ_CUSTOMER_CODE_DUPLICATE；`CustomerController.java` 补 @Auditable + 权限码 masterdata:customer:*→biz:customer:*；`MockAuthAdapter.java` BIZ_PERMISSIONS 对齐；（3）Blocker 修复：B1 V*.sql 已存在、B2 测试依赖补齐、B3 错误码修正、B4 @Auditable 补齐、B5 权限码对齐、B6 RealtimeProperties Bean 未注册、B7 cleanup SQL 列名修正。已知偏差：DEV-L180-001 CT-2 认证失败 @Disabled（Mock 模式限制）；DEV-L180-002 仅覆盖 createCustomer；DEV-L180-003 AuditableAspect afterJson 序列化警告；DEV-L180-004 CI contract job 已集成 CT。验收结论：**PASS**。 | `58-后端API逐接口任务清单`、`59-测试矩阵与验收用例详设`、`23` |
| 2026-07-23 | v1.0 GA2 CT-Customer 域剩余 4 接口契约测试落地验收 | 复用 L180 基类落地 updateCustomer/deleteCustomer/listCustomer/getCustomer，34/34 PASS（30 + 4 Skipped） | （1）新建 4 个测试类：`CTUpdateCustomerTest.java`（10 用例，versionedUpdate 乐观锁）、`CTDeleteCustomerTest.java`（7 用例，guardedDelete 自然幂等）、`CTListCustomerTest.java`（9 用例，queryPage + 数据范围）、`CTGetCustomerTest.java`（8 用例，queryOne + 字段级脱敏）；（2）修改 3 个文件：`CustomerController.java` page()/get() 补 @RequiresPermission（biz:customer:list/detail）；`CustomerService.java` 注入 AuthAdapter + getCustomer() 按 biz:customer:phone:view 字段权限脱敏；`MockAuthAdapter.java` BIZ_PERMISSIONS 补 detail/delete/phone:view，VIEWER_PERMISSIONS 补 detail；（3）Blocker 修复：B1 任务描述错误码偏差（BIZ-404001→BIZ-404002、BIZ-409006→SYS-409001）、B2 权限码偏差（biz:customer:view→detail）、B3 CustomerController 缺少权限注解、B4 详情未按字段权限脱敏、B5 MockAuthAdapter 权限码不完整、B6 编译警告。验收结论：**PASS**。 | `58-后端API逐接口任务清单`、`59-测试矩阵与验收用例详设`、`23` |
| 2026-07-23 | v1.0 GA2 Web Playwright E2E 套件落地验收 | 新增 Playwright E2E 基础设施与客户管理端到端测试，18/18 PASS（耗时 2.0 分钟） | （1）新建 9 个文件：`web-admin/playwright.config.ts`、`.env.e2e`、`e2e/helpers/selectors.ts`、`e2e/helpers/auth.ts`、`e2e/helpers/customer.ts`、`e2e/auth.spec.ts`、`e2e/customer-crud.spec.ts`、`e2e/customer-permission.spec.ts`、`e2e/customer-validation.spec.ts`；（2）覆盖 4 类场景：认证流程 4 用例（admin/viewer 登录、错误密码、退出）、客户 CRUD 5 用例（create/update/delete/list + 重复编码）、权限控制 4 用例（按钮可见性 + 直调 API 403/200）、表单校验 5 用例（必填、枚举、取消）；（3）发现 6 项缺陷（5 前端 + 1 后端错误码），受约束未修改 `web-admin/src/**`，customer-crud 用 try/catch 兜底通过；缺陷清单已归档 evidence。已知偏差：DEV-L183-001 5 项前端业务代码缺陷待前端批次修复；DEV-L183-002 缺陷 6 后端错误码后续由 GA2-L180/L181 确认修复。验收结论：**PASS**（带已知缺陷清单）。 | `58-后端API逐接口任务清单`、`59-测试矩阵与验收用例详设`、`91-Web基础后台逐页交互详设`、`23` |
| 2026-07-23 | v1.0 GA2 前端缺陷修复 + Playwright E2E 重跑落地验收 | 修复 L183 发现的前端缺陷 1~5，E2E 18/18 PASS 且移除 try/catch 改硬断言 | （1）修改 5 个前端缺陷：`web-admin/src/api/customer.ts` 去掉双重 `/api/v1` 前缀；`CustomerList.vue` + `api/types.ts` contactPerson→contactName；`CustomerList.vue` status ACTIVE/INACTIVE→ENABLED/DISABLED；`CustomerList.vue` v-permission masterdata:customer:*→biz:customer:*；`.env.development` VITE_API_BASE_URL 8080→相对路径 `/api/v1` 走 Vite proxy；（2）确认缺陷 6（后端 BIZ-409005）已在 GA2-L180 修复；（3）E2E 重跑结果 18/18 PASS，customer-crud.spec.ts 5 用例全部硬断言通过（成功 toast、列表行可见、错误 toast），总耗时从 2.0 分钟降至 1.7 分钟。已知偏差：无新增偏差。验收结论：**PASS**。 | `58-后端API逐接口任务清单`、`91-Web基础后台逐页交互详设`、`23` |
| 2026-07-23 | v1.0 GA2 Dict 字典域 CT-<operationId> 契约测试套件落地验收 | 落地 Dict 域 5 个 operationId CT 测试，45/45 PASS（40 + 5 Skipped） | （1）新建 5 个测试类：`CTCreateDictTypeTest.java`（11 用例）、`CTUpdateDictTypeTest.java`（9 用例）、`CTDeleteDictTypeTest.java`（7 用例）、`CTListDictTypeTest.java`（9 用例）、`CTListDictItemTest.java`（9 用例）；（2）严格复用 L180 AbstractContractTest + application-test.yml + Docker 容器复用；（3）覆盖 createDictType/updateDictType/deleteDictType/listDictTypes/listDictItems，验证权限拒绝、参数校验、重复编码、乐观锁、逻辑删除、审计落库、traceId 透传、数据范围；（4）Blocker 修复：DictType 缺少参数校验注解（@NotBlank/@Pattern）、dictType 唯一索引冲突等。已知偏差：DEV-L185-001 5 个 CT-2 认证失败用例 @Disabled（Mock 模式限制）。验收结论：**PASS**。 | `58-后端API逐接口任务清单`、`59-测试矩阵与验收用例详设`、`23` |
| 2026-07-23 | v1.0 GA2 Product 商品域 CT-<operationId> 契约测试套件落地验收 | 落地 Product 域 5 个 operationId CT 测试，45/45 PASS（40 + 5 Skipped） | （1）新建 5 个测试类：`CTCreateProductTest.java`（11 用例）、`CTUpdateProductTest.java`（10 用例）、`CTDeleteProductTest.java`（7 用例）、`CTListProductTest.java`（9 用例）、`CTGetProductTest.java`（8 用例）；（2）复用 L180/L181 基类与 Docker 容器；（3）覆盖 createProduct/updateProduct/deleteProduct/listProducts/getProduct，验证 uniqueCreate 重复编码 BIZ-409006、versionedUpdate 乐观锁 SYS-409001、guardedDelete 自然幂等、read 分页过滤排序、字段完整性；（4）权限码对齐 biz:product:list/detail/add/edit/delete/import/export。已知偏差：DEV-L186-001 5 个 CT-2 认证失败用例 @Disabled（Mock 模式限制）。验收结论：**PASS**。 | `58-后端API逐接口任务清单`、`59-测试矩阵与验收用例详设`、`23` |
| 2026-07-23 | v1.0 GA2 SysConfig 参数配置域 CT-<operationId> 契约测试套件落地验收 | 落地 SysConfig 域 5 个 operationId CT 测试，44/44 PASS（39 + 5 Skipped） | （1）新建 5 个测试类：`CTCreateSysConfigTest.java`（11 用例）、`CTUpdateSysConfigTest.java`（9 用例）、`CTDeleteSysConfigTest.java`（7 用例）、`CTListSysConfigTest.java`（9 用例）、`CTGetSysConfigTest.java`（8 用例）；（2）复用 L180 基类与容器；（3）覆盖 createConfig/updateConfig/deleteConfig/listConfigs/getConfig，验证 configKey 不可变、敏感配置脱敏（sensitive=true→configValue=******）、参数校验、乐观锁、重复 key、审计落库；（4）Blocker 修复：SysConfig 实体缺少 @NotBlank/@Pattern 参数校验注解。已知偏差：DEV-L187-001 5 个 CT-2 认证失败用例 @Disabled（Mock 模式限制）。验收结论：**PASS**。 | `58-后端API逐接口任务清单`、`59-测试矩阵与验收用例详设`、`23` |
| 2026-07-23 | v1.0 GA2 File 文件管理域 CT-<operationId> 契约测试套件落地验收 | 落地 File 域 5 个 operationId CT 测试，40/40 PASS（35 + 5 Skipped） | （1）新建 5 个测试类：`CTUploadFileTest.java`（9 用例）、`CTDownloadFileTest.java`（7 用例）、`CTListFileTest.java`（9 用例）、`CTDeleteFileTest.java`（7 用例）、`CTPreviewFileTest.java`（8 用例）；（2）复用 L180 基类与容器；（3）覆盖 uploadFile/downloadFile/listFiles/deleteFile/previewFile，验证 multipart 上传、非法类型拒绝 FILE-400001、校验和唯一性、预签名下载 URL、逻辑删除、数据范围 viewer TENANT、审计落库；（4）权限码对齐 system:file:upload/list/download/preview/delete。已知偏差：DEV-L188-001 5 个 CT-2 认证失败用例 @Disabled（Mock 模式限制）。验收结论：**PASS**。 | `58-后端API逐接口任务清单`、`59-测试矩阵与验收用例详设`、`23` |
| 2026-07-23 | v1.0 GA2 BizRequest 业务申请单域 CT-<operationId> 契约测试套件落地验收 | 落地 BizRequest 域 6 个 operationId CT 测试，49/49 PASS（43 + 6 Skipped） | （1）新建 6 个测试类：`CTCreateBizRequestTest.java`（7 用例）、`CTUpdateBizRequestTest.java`（9 用例）、`CTDeleteBizRequestTest.java`（7 用例）、`CTGetBizRequestTest.java`（8 用例）、`CTListBizRequestTest.java`（9 用例）、`CTApproveBizRequestTest.java`（9 用例）；（2）通过 Docker Maven 容器（maven:3.9-eclipse-temurin-25）在 yutong_default 网络运行；（3）覆盖 createBizRequest/updateBizRequest/deleteBizRequest/getBizRequest/listBizRequests/approveBizRequest，验证草稿创建、状态冲突 BIZ-409001、workflowAction 审批 SUBMITTED→APPROVED、数据范围拒绝 AUTH-403002、viewer 敏感字段脱敏、乐观锁；（4）权限码对齐 biz:request:add/edit/delete/list/detail/approve。已知偏差：DEV-L189-001 6 个 CT-2 认证失败用例 @Disabled（Mock 模式限制）。验收结论：**PASS**。 | `58-后端API逐接口任务清单`、`59-测试矩阵与验收用例详设`、`18-样例业务详细设计`、`23` |
| 2026-07-24 | v1.0 GA2 CT-<operationId> 契约测试套件全量落地验收 | 96 个 CT 测试类 / 66 operationId / 672 用例全量运行，672/672 PASS（552 + 120 Skipped） | （1）通过 Docker Maven 容器执行 `mvn -pl yutong-boot test -Dtest=com.yutong.boot.contract.CT*`，BUILD SUCCESS，总耗时 2 分 20 秒；（2）首轮 26 失败 → 0 失败，修复 8 个源文件：`SysJobLog.java` LocalDateTime→OffsetDateTime（12 失败）、`FileService.java` bind 补 setId（3 失败）、`PlatformMetrics.java` scenario null 防护（2 失败）、`WorkbenchController.java` stats 补 traceId（4 失败）、`BizRequestApplicationService.java` reject opinion 空值校验前置（2 失败）、`GlobalExceptionHandler.java` 处理 MissingServletRequestParameterException（1 失败）、`MobileController.java` resolveScan URL 解码（1 失败）、`FieldMaskingService.java` FULL_MASK "***"→"******"（1 失败）；（3）模块覆盖：System 38 类、Business 24 类、Lowcode 16 类、AI 5 类、Mobile 13 类；（4）通用覆盖矩阵 14 类场景全部 PASS。已知偏差：DEV-L190-001 120 个 CT-2 认证失败 @Disabled；DEV-L190-002 66/94 operationId 覆盖；DEV-L190-003 AuditableAspect afterJson 序列化警告；DEV-L190-004 通过 Docker Maven 容器运行；DEV-L190-005 FULL_MASK 改为 6 星。验收结论：**PASS**。 | `58-后端API逐接口任务清单`、`59-测试矩阵与验收用例详设`、`contracts/registries/operation-policies.yaml`、`contracts/openapi/openapi.yaml`、`23` |
"""
with p.open('a', encoding='utf-8') as f:
    f.write(rows)
print('Appended', len(rows), 'chars')
